### ISSUE TITLE
user/group identity of the process

### ISSUE THREAD

**Issue by skoro** [skoro/multirun#11]
Add to the process configuration `uid` and `gid` parameters:
```yaml
spawn:
   proc1:
      uid: 1000
      gid: 1000
```
These parameters are of number type.
