### ISSUE TITLE
Process dependency or priority

### ISSUE THREAD

**Issue by skoro** [skoro/multirun#15]
Allow to set the process priority like this:
```yaml
task1:
   command: task1
task2:
   after: task1
task3:
  after: task1
task4:
  after: task2
```

```
task1 ---> task2 ---> task4
   +------> task3
```

Attention should be paid that the parent process can be started with delay or it could be failed to start but has `restart` parameter.
