### ISSUE TITLE
Simple cron implementation ?

### ISSUE THREAD

**Issue by skoro** [skoro/multirun#16]
As an idea to extend: cron feature:
```yaml
cron:
  sync:
    command: 'some-sync-command'
    every: 1h | 30m | 20s   <-- time
```
In addition to `spawn` configuration, there will be `cron` one, allowing to define what processes to run in what time.
